//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMetropolitano.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetropolitanoEntities1 : DbContext
    {
        public MetropolitanoEntities1()
            : base("name=MetropolitanoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RECARGA> RECARGAs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TARJETA> TARJETAs { get; set; }
        public virtual DbSet<TIPO_TARJETA> TIPO_TARJETA { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIO_GENERAL> USUARIO_GENERAL { get; set; }
        public virtual DbSet<USUARIO_UNIVERSITARIO> USUARIO_UNIVERSITARIO { get; set; }
    }
}
