//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMetropolitano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECARGA
    {
        public string COD_RECARGA { get; set; }
        public System.DateTime FE_RECARGA { get; set; }
        public decimal MONTO_RECARGA { get; set; }
        public string COD_TARJETA_RECARGA { get; set; }
    
        public virtual TARJETA TARJETA { get; set; }
    }
}
