//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMetropolitano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TARJETA()
        {
            this.RECARGAs = new HashSet<RECARGA>();
        }
    
        public string COD_TARJETA { get; set; }
        public string ESTADO_TARJETA { get; set; }
        public Nullable<decimal> SALDO_TARJETA { get; set; }
        public Nullable<System.DateTime> FE_EXP_TARJETA { get; set; }
        public string COD_TIPO_TARJETA { get; set; }
        public string COD_USUARIO_TARJETA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECARGA> RECARGAs { get; set; }
        public virtual TIPO_TARJETA TIPO_TARJETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public string CODCARNET { get; set; }
        public string NRO_TC { get; set; }
        public string CVV_TC { get; set; }
        public string VENCIMIENTO_TC { get; set; }
        public decimal MONTO { get; set; }
        public string TITULAR_TC { get; set; }
    }
}
