//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMetropolitano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.TARJETAs = new HashSet<TARJETA>();
            this.USUARIO_GENERAL = new HashSet<USUARIO_GENERAL>();
            this.USUARIO_UNIVERSITARIO = new HashSet<USUARIO_UNIVERSITARIO>();
        }
    
        public string COD_USUARIO { get; set; }
        public string PASSWORD_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string GENERO_USUARIO { get; set; }
        public string TIPO_DOC_USUARIO { get; set; }
        public string DIRECCION_USUARIO { get; set; }
        public string DISTRITO_USUARIO { get; set; }
        public System.DateTime FECHA_NAC_USUARIO { get; set; }
        public string CELULAR_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA> TARJETAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_GENERAL> USUARIO_GENERAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_UNIVERSITARIO> USUARIO_UNIVERSITARIO { get; set; }
    }
}
