//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suneduWSREST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARNET
    {
        public string COD_CARNET { get; set; }
        public string DNI_ALUMNO { get; set; }
        public string UNI_ALUMNO { get; set; }
        public System.DateTime FECEXP_ALUMNO { get; set; }
    }
}
